### ISSUE TITLE
[INFO] Generating "Tag List" report      --- taglist-maven-plugin:3.0.0:taglist [WARNING] Using legacy tag format.  This is not recommended.

### ISSUE THREAD

**Issue by patpatpat123** [mojohaus/taglist-maven-plugin#103]
Hello team,

This is my first issue in this repo.
If nothing else, wanted to say big thanks for this project.

When running this as part of ```mvn site``` command, I am seeing this:

```
[INFO] Generating "Tag List" report      --- taglist-maven-plugin:3.0.0:taglist
[WARNING] Using legacy tag format.  This is not recommended.
```

The thing is, I have no tag at all in my code.
How do I fix this warning please?
i.e, how do I not use legacy format?

Thank you

**Comment by bmarwell** [comment]
I think it's how you configure the plugin. Can you check with the examples?

**Comment by jberiksen** [comment]
Hello @patpatpat123 

I know this post is 9 month old, I would like to help.

You find the new configuration here:
https://www.mojohaus.org/taglist-maven-plugin/usage.html

**Comment by patpatpat123** [comment]
Thank you for your constructive answer @jberiksen, working now. 

Closing, good day!
