### ISSUE TITLE
Report table not showing correctly

### ISSUE THREAD

**Issue by aitor-binaryshock** [mojohaus/taglist-maven-plugin#109]
Hi!!!

If you use the plugin along with maven site plugin version 4.0.0-M8, the table is not shown correctly.

It would be great to fix it.

Lot of thanks!!!

**Comment by walnikster** [comment]
Spotted the same issue with 4.0.0-M12. Would be great to get this fixed. It prevents to switch to site version 4.0

Thank you

**Comment by slawekjaranowski** [comment]
@michael-o - any hints how to fix

**Comment by michael-o** [comment]
Here it is: https://cwiki.apache.org/confluence/display/MAVEN/Towards+Doxia+2.0.0+Stack#TowardsDoxia2.0.0Stack-ReportingPluginMaintainers

Basically, I do not recommend mix new site plugin with old (pre-Doxia 2.0.0) reporting plugins. The behavior is undefined.

**Comment by slawekjaranowski** [comment]
This should be fixed by: #145
