### ISSUE TITLE
Version 3.0 is not on Maven Central

### ISSUE THREAD

**Issue by michael-o** [mojohaus/taglist-maven-plugin#60]
Git tag is created, website is updated, but cannot find here: https://repo1.maven.org/maven2/org/codehaus/mojo/taglist-maven-plugin/
I need it for an upcoming MSITE/MJAVADOC update to fix issues with Doxia. I also don't have access ot the staging repos on oss.s.o, but that's another story.

**Comment by bmarwell** [comment]
Hi @michael-o, vote is still in progress and not ended yet.
https://groups.google.com/g/mojohaus-dev/c/Xggo0Eq7ArA

The release is markt as pre-release for this reason according to the deployment guide: https://www.mojohaus.org/development/performing-a-release.html

**Comment by michael-o** [comment]
> Hi @michael-o, vote is still in progress and not ended yet. https://groups.google.com/g/mojohaus-dev/c/Xggo0Eq7ArA
> 
> The release is markt as pre-release for this reason according to the deployment guide: https://www.mojohaus.org/development/performing-a-release.html

Ah OK, this makes sense. You obviously need a staging site ;-)

**Comment by bmarwell** [comment]
> Ah OK, this makes sense. You obviously need a staging site ;-)

Yes, maybe. But then, these plugins are released only every now and then... so it might not matter that much at all.

I was going to do about two more releases and then lay it dormant again. ;-)

**Comment by michael-o** [comment]
Thanks, a change in Maven Site Plugin is looking forward to it.

**Comment by bmarwell** [comment]
Released, will be available in a few hours.
