### ISSUE TITLE
Exclude source files

### ISSUE THREAD

**Issue by tguduru** [mojohaus/taglist-maven-plugin#7]
I couldn't find any option to exclude a java source file from checking the tags. Do we have an option already in the plugin? If yes can anyone please share how to do it?

Usually we don't want to exclude any sources from static analysis but some sources are generated by code generator tools which may document tags based on the input template for those tools.

If not can this be added, probably i can contribute.

**Comment by khmarbaise** [comment]
Hm..first answer to your question is No there is no such option to exclude files from taglist-maven-plugin....

But now my question: Into which directory is the source being generated ?  `src/main` ?

**Comment by tguduru** [comment]
yes, they will be in src/main

**Comment by khmarbaise** [comment]
This is exactly what I expected...which is simply wrong. Never should any kind of generation (wsdl/xlc etc.) every generate into src/main...which is under version control which mean changing all the time the checkin state of the files/or at least changing the state...The default is to generated into `target/generated-source-...` whatever...will simply solve the problem...

**Comment by tguduru** [comment]
generated sources is an example, but do you see any use case for exclude some files?

in my use case i am seeing it and probably looking for adding some rules to exclude stated files

**Comment by agaengel** [comment]
I would also like to exclude some files 
We have some file in the resources that is payload for our artifact.
One file in the resources is sourcecode with todos and these are now in our report.

Regards
Alex

**Comment by bmarwell** [comment]
@tguduru @agaengel I am planning to do a Maven 3 release (https://github.com/mojohaus/taglist-maven-plugin/releases/tag/untagged-dcacf047d4b8d156dd04). If you need this enhancement, kindly open a pull request. Otherwise we can also make it into 3.1.0.
