### ISSUE TITLE
legacy tags

### ISSUE THREAD

**Issue by delanym** [mojohaus/taglist-maven-plugin#74]
./mvnw taglist:taglist

gives `[WARNING] Using legacy tag format.  This is not recommended.`

What is it referring to: something in the plugin configuration or something in my code?

**Comment by LIttleAncientForestKami** [comment]
In version 2.4 a change was made. Previous configs (I think) do not work anymore. You now need to use a MUCH more verbose config to get the plugin to work. See usage page for the plugin for the new config.

NOTE: this message also appears if you run the plugin without config, like so  `mvn taglist:taglist`

Workaround:

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>taglist-maven-plugin</artifactId>
        <version>2.3</version>
        <configuration>
          <tags>
            <tag>FIXME</tag>
            <tag>TODO</tag>
          </tags>
        </configuration>
      </plugin>
```

Downgrades the version to last with older config and use it like so. Beware: TODO and todo and tOdo and toDo are different and need to be marked separately. New config deals with that, if you so want.
