### ISSUE TITLE
Why is the taglist plugin trying to write to the windows registry?

### ISSUE THREAD

**Issue by spyhunter99** [mojohaus/taglist-maven-plugin#8]
First attempt using this and i'm getting the following warning

Could not open/create prefs root node Software/JavaSoft/Prefs at root 0x80000002. Windows.RegCreateKeyEx(...) returns error code 5

**Comment by spyhunter99** [comment]
after further investigation it isn't this plugin. must be something else in maven land.

**Comment by khmarbaise** [comment]
That definitively neither this plugin nor Maven cause maven will never do an access to the registry in Windows...

**Comment by spyhunter99** [comment]
https://github.com/julienvollering/MIAmaxent/issues/1 https://bugs.openjdk.java.net/browse/JDK-8139507
looks like it may be a java issue.
